name:                writeup
version:             0.1.0.0
github:              "s-zeng/PLACEHOLDER"
license:             BSD3
author:              "Simon Zeng"
maintainer:          "simon.zeng@tqtezos.com"
copyright:           "2020 Simon Zeng, TQ Tezos"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/contracts#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - lorentz
  - morley
  - universum

executables:
  operatoradmin-exe:
    main:                Main.lhs
    source-dirs:         app
    build-depends: base, markdown-unlit
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -pgmL markdown-unlit
    dependencies:
    - writeup
    - lorentz
    - morley
    - universum
    - bytestring

tests:
  contracts-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - writeup
    - lorentz
    - universum
    - morley
